#!/bin/bash

#colors
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
NC=$(tput sgr0)
#check if vm exists
function vm_exist() {
  if_exists=$(virsh list --all | grep -o "$1")

  if [ -z "$if_exists" ]; then
    echo "$RED The VM does not exist $NC"
    exit 1

  fi
}

#help
function help() {

  echo "**************************"
  echo "* usage: enter the name  *"
  echo "*   your vm. that's it   *"
  echo "**************************"

}

#check if the user is in the libvirt group
function check_groups() {
  group="libvirt"
  get_group=$(groups $(whoami) | grep -o "libvirt")
  if [ "$get_group" == "$group" ]; then
    echo -e "$GREEN[+] you are in the right group...attempting to start vm $NC"

  else

    echo -e "$RED[+] you are not in the libvirt group. please contact your sysadmin...or just add yourself to it $NC"
    exit 1
  fi
}

#main function to start the vms
function start_vm() {
  #checking if the user is in the right group and if the vm exists
  check_groups
  vm_exist "$1"
  #check if the vm is running
  vm_state_running="$(virsh domstate "$1")"
  if [ "$vm_state_running" == "running" ]; then
    echo -e "$RED[+] $1 is already started $NC"
    exit 0
  fi
  #start the vm
  while [ "$vm_state_running" != "running" ]; do
    printf "\n"
    virsh start "$1" >/dev/null
    vm_state_running="$(virsh domstate "$1")"
    if [ $vm_state_running != "running" ]; then
      echo -e "$RED VM seems to have failed to start. VM state: $vm_state_running $NC"
      exit 1
    else
      echo -e "$GREEN[+] VM Started successfully $NC"
    fi

  done

}

#main logic to start the script
if [ "-h" == "$1" ] || [[ $# -eq 0 ]]; then
  help
else
  start_vm "$1"
fi
