#!/bin/bash

#colors
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)

#main function to start the vms
function start_vm() {
  vm_state_running="$(virsh domstate $1 | grep -o running)"
  while [ "$vm_state_running" != "running" ]; do
    printf "\n\n"
    virsh start $1
    echo -e "$GREEN[+] $1 started"
    exit
  done

  echo -e "$RED $1 is already started"
  exit
}

#help
function help() {

  echo "**************************"
  echo "* usage: enter the name  *"
  echo "*   your vm. that's it   *"
  echo "**************************"

}

#check if the user is in the libvirt group
function check_groups() {
  group="libvirt"
  if [ 'groups $(whoami) | grep -o "libvirt" == "$group"' ]; then
    echo -e "$GREEN[+] you are in the right group, starting your vm now"
    sleep 0.5
    start_vm $1

  else
    echo -e "$RED[+] you are not in the libvirt group. please contact your sysadmin"

  fi
}

if [ "-h" == $1 ] || [[ $# -eq 0 ]]; then
  help
else
  check_groups $1

fi
